services:
  web:
    image: shoppingtickets
    build: .
    restart: always
    env_file:
      - ./.env
    expose:
      - 8000
    volumes:
      - .:/data
    command: > 
      bash -c "python manage.py migrate
      && gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    depends_on:
      - redis

  redis:
    image: redis:7

  nginx:
    build: ./nginx
    restart: always
    ports:
      - ${NGINX_PORT}:80
    depends_on:
      - web
