services:
  web:
    image: shoppingtickets
    build: .
    restart: always
    env_file:
      - ./.env
    expose:
      - 8000
    volumes:
      - .:/data
    command: > 
      bash -c "python manage.py migrate
      && gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    depends_on:
      - redis

  redis:
    image: redis:7

  proxy:
    build: ./docker/proxy
    restart: always
    env_file:
      - ./.env
    ports:
      - 80:80
      - 443:443
    volumes:
      - certbot-web:/vol/www
      - proxy-dhparams:/vol/proxy
      - certbot-certs:/etc/letsencrypt
    depends_on:
      - web
  
  certbot:
    build: ./docker/certbot
    command: echo "Skipping..."
    env_file:
      - ./.env
    volumes:
      - certbot-web:/vol/www
      - certbot-certs:/etc/letsencrypt/
    depends_on:
      - proxy
  
volumes:
  certbot-web:
  proxy-dhparams:
  certbot-certs:
