services:
  web:
    build: .
    ports:
      - '8000:8000'
    volumes:
      - .:/data
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - migration
  
  migration:
    command: python manage.py migrate
