services:
  web:
    container_name: web
    image: shoppingtickets
    build: .
    restart: always
    env_file:
      - ./.env
    expose:
      - 9000
    volumes:
      - .:/data
    command: >
      bash -c "python manage.py migrate
      && gunicorn shopping_tickets.wsgi:application --bind 0.0.0.0:9000"
